# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bill.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import test
import mysql.connector as MC
con=MC.connect(host='localhost',user='root',passwd='',database='hotel')
cur=con.cursor()
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BillWindow(object):
    def __init__(self,z):
        self.d=z
    def setupUi(self, BillWindow):
        BillWindow.setObjectName("BillWindow")
        BillWindow.resize(800, 581)
        self.centralwidget = QtWidgets.QWidget(BillWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(0, 0, 801, 591))
        self.l1.setText("")
        self.l1.setPixmap(QtGui.QPixmap(":/iage/bill payment .jpg"))
        self.l1.setScaledContents(True)
        self.l1.setObjectName("l1")
        self.t1 = QtWidgets.QTableWidget(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(90, 60, 601, 111))
        self.t1.setObjectName("t1")
        self.t1.setColumnCount(6)
        self.t1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.t1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.t1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.t1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.t1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.t1.setHorizontalHeaderItem(5, item)
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(320, 10, 121, 31))
        self.l2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l2.setObjectName("l2")
        self.t2 = QtWidgets.QTableWidget(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(240, 230, 311, 101))
        self.t2.setObjectName("t2")
        self.t2.setColumnCount(3)
        self.t2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.t2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.t2.setHorizontalHeaderItem(2, item)
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(310, 180, 161, 31))
        self.l3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(200, 360, 131, 21))
        self.l4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l4.setObjectName("l4")
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(240, 390, 31, 21))
        self.l5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l5.setObjectName("l5")
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(220, 420, 71, 21))
        self.l6.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l6.setObjectName("l6")
        self.e1 = QtWidgets.QLineEdit(self.centralwidget)
        self.e1.setGeometry(QtCore.QRect(370, 360, 171, 21))
        self.e1.setObjectName("e1")
        self.e2 = QtWidgets.QLineEdit(self.centralwidget)
        self.e2.setGeometry(QtCore.QRect(370, 420, 171, 21))
        self.e2.setObjectName("e2")
        self.p1 = QtWidgets.QPushButton(self.centralwidget)
        self.p1.setGeometry(QtCore.QRect(330, 450, 61, 31))
        self.p1.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.p1.setObjectName("p1")
        self.p1.clicked.connect(self.pay)
        self.l7 = QtWidgets.QLabel(self.centralwidget)
        self.l7.setGeometry(QtCore.QRect(130, 490, 471, 31))
        self.l7.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"background-color: rgb(255, 255, 255);")
        self.l7.setText("")
        self.l7.setObjectName("l7")
        BillWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BillWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        BillWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BillWindow)
        self.statusbar.setObjectName("statusbar")
        BillWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BillWindow)
        QtCore.QMetaObject.connectSlotsByName(BillWindow)
        sql="select * from Booking where Email='{}' and  Paid='{}'".format(self.d,'No')
        cur.execute(sql)
        r=cur.fetchall()
        for i in r:
            v=self.t1.rowCount()
            self.t1.insertRow(v)
            self.t1.setItem(v,0,QtWidgets.QTableWidgetItem(str(i[1])))
            self.t1.setItem(v,1,QtWidgets.QTableWidgetItem(str(i[2])))
            self.t1.setItem(v,2,QtWidgets.QTableWidgetItem(str(i[3])))
            self.t1.setItem(v,3,QtWidgets.QTableWidgetItem(str(i[4])))
            self.t1.setItem(v,4,QtWidgets.QTableWidgetItem(str(i[5])))
            self.t1.setItem(v,5,QtWidgets.QTableWidgetItem(str(i[6])))
        sql="select * from Food where Email='{}' and Paid='{}'".format(self.d,'No')
        cur.execute(sql)
        r=cur.fetchall()
        for i in r:
            v=self.t2.rowCount()
            self.t2.insertRow(v)
            self.t2.setItem(v,0,QtWidgets.QTableWidgetItem(str(i[1])))
            self.t2.setItem(v,1,QtWidgets.QTableWidgetItem(str(i[2])))
            self.t2.setItem(v,2,QtWidgets.QTableWidgetItem(str(i[3])))
    def pay(self):
        sql="update Booking set Paid='{}' where Email='{}'".format('Yes',self.d)
        cur.execute(sql)
        con.commit()
        sql="update Food set Paid='{}' where Email='{}'".format('Yes',self.d)
        cur.execute(sql)
        con.commit()
        self.l7.setText("Payment Succesfully recieved.")
    def retranslateUi(self, BillWindow):
        _translate = QtCore.QCoreApplication.translate
        BillWindow.setWindowTitle(_translate("BillWindow", "Bill"))
        item = self.t1.horizontalHeaderItem(0)
        item.setText(_translate("BillWindow", "Room No."))
        item = self.t1.horizontalHeaderItem(1)
        item.setText(_translate("BillWindow", "Room Type"))
        item = self.t1.horizontalHeaderItem(2)
        item.setText(_translate("BillWindow", "Check In Date"))
        item = self.t1.horizontalHeaderItem(3)
        item.setText(_translate("BillWindow", "Check Out Date"))
        item = self.t1.horizontalHeaderItem(4)
        item.setText(_translate("BillWindow", "Amount"))
        item = self.t1.horizontalHeaderItem(5)
        item.setText(_translate("BillWindow", "Paid"))
        self.l2.setText(_translate("BillWindow", "Booking Bill:"))
        item = self.t2.horizontalHeaderItem(0)
        item.setText(_translate("BillWindow", "Food Items"))
        item = self.t2.horizontalHeaderItem(1)
        item.setText(_translate("BillWindow", "Amount"))
        item = self.t2.horizontalHeaderItem(2)
        item.setText(_translate("BillWindow", "Paid"))
        self.l3.setText(_translate("BillWindow", "Food Order Bill:"))
        self.l4.setText(_translate("BillWindow", "Card Number:"))
        self.l5.setText(_translate("BillWindow", "OR"))
        self.l6.setText(_translate("BillWindow", "UPI ID:"))
        self.p1.setText(_translate("BillWindow", "Pay"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BillWindow = QtWidgets.QMainWindow()
    ui = Ui_BillWindow()
    ui.setupUi(BillWindow)
    BillWindow.show()
    sys.exit(app.exec_())
