# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import test
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as MC
con=MC.connect(host='localhost',user='root',passwd='',database='hotel')
cur=con.cursor()

class Ui_HistoryWindow(object):
    def __init__(self,v):
        self.w=v
    def setupUi(self, HistoryWindow):
        HistoryWindow.setObjectName("HistoryWindow")
        HistoryWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(HistoryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(0, 0, 811, 561))
        self.l1.setText("")
        self.l1.setPixmap(QtGui.QPixmap(":/iage/History.png"))
        self.l1.setScaledContents(True)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(280, 20, 161, 31))
        self.l2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l2.setObjectName("l2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(80, 60, 601, 171))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.table2 = QtWidgets.QTableWidget(self.centralwidget)
        self.table2.setGeometry(QtCore.QRect(220, 290, 311, 171))
        self.table2.setObjectName("table2")
        self.table2.setColumnCount(3)
        self.table2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(2, item)
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(280, 250, 191, 31))
        self.l3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l3.setObjectName("l3")
        HistoryWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HistoryWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        HistoryWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HistoryWindow)
        self.statusbar.setObjectName("statusbar")
        HistoryWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HistoryWindow)
        QtCore.QMetaObject.connectSlotsByName(HistoryWindow)
        sql="select * from Booking where Email='{}'".format(self.w)
        cur.execute(sql)
        r=cur.fetchall()
        for i in r:
            v=self.tableWidget.rowCount()
            self.tableWidget.insertRow(v)
            self.tableWidget.setItem(v,0,QtWidgets.QTableWidgetItem(str(i[1])))
            self.tableWidget.setItem(v,1,QtWidgets.QTableWidgetItem(str(i[2])))
            self.tableWidget.setItem(v,2,QtWidgets.QTableWidgetItem(str(i[3])))
            self.tableWidget.setItem(v,3,QtWidgets.QTableWidgetItem(str(i[4])))
            self.tableWidget.setItem(v,4,QtWidgets.QTableWidgetItem(str(i[5])))
            self.tableWidget.setItem(v,5,QtWidgets.QTableWidgetItem(str(i[6])))
        sql="select * from Food where Email='{}'".format(self.w)
        cur.execute(sql)
        r=cur.fetchall()
        for i in r:
            v=self.table2.rowCount()
            self.table2.insertRow(v)
            self.table2.setItem(v,0,QtWidgets.QTableWidgetItem(str(i[1])))
            self.table2.setItem(v,1,QtWidgets.QTableWidgetItem(str(i[2])))
            self.table2.setItem(v,2,QtWidgets.QTableWidgetItem(str(i[3])))
    def retranslateUi(self, HistoryWindow):
        _translate = QtCore.QCoreApplication.translate
        HistoryWindow.setWindowTitle(_translate("HistoryWindow", "History-Page"))
        self.l2.setText(_translate("HistoryWindow", "Booking History:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("HistoryWindow", "Room No."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("HistoryWindow", "Room Type"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("HistoryWindow", "Check In Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("HistoryWindow", "Check Out Date"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("HistoryWindow", "Amount"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("HistoryWindow", "Paid"))
        item = self.table2.horizontalHeaderItem(0)
        item.setText(_translate("HistoryWindow", "Food Items"))
        item = self.table2.horizontalHeaderItem(1)
        item.setText(_translate("HistoryWindow", "Amount"))
        item = self.table2.horizontalHeaderItem(2)
        item.setText(_translate("HistoryWindow", "Paid"))
        self.l3.setText(_translate("HistoryWindow", "Food Order History:"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HistoryWindow = QtWidgets.QMainWindow()
    ui = Ui_HistoryWindow()
    ui.setupUi(HistoryWindow)
    HistoryWindow.show()
    sys.exit(app.exec_())
