# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from food import Ui_FoodWindow
from room import Ui_RoomWindow
from history import Ui_HistoryWindow
from bill import Ui_BillWindow
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def __init__(self,v):
        self.a=v
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(735, 635)
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(0, 0, 861, 641))
        self.l1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.l1.setText("")
        self.l1.setScaledContents(True)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(10, 0, 341, 201))
        self.l2.setText("")
        self.l2.setPixmap(QtGui.QPixmap(":/iage/Room Booking.jpg"))
        self.l2.setScaledContents(True)
        self.l2.setObjectName("l2")
        self.p1 = QtWidgets.QPushButton(self.centralwidget)
        self.p1.setGeometry(QtCore.QRect(40, 210, 261, 51))
        self.p1.setStyleSheet("font: 26pt \"Noto Mono\";\n"
"background-color: rgb(124, 200, 118);")
        self.p1.setObjectName("p1")
        self.p1.clicked.connect(self.Room)
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(380, 0, 341, 201))
        self.l3.setText("")
        self.l3.setPixmap(QtGui.QPixmap(":/iage/restaurant.jpg"))
        self.l3.setScaledContents(True)
        self.l3.setObjectName("l3")
        self.p2 = QtWidgets.QPushButton(self.centralwidget)
        self.p2.setGeometry(QtCore.QRect(450, 210, 221, 51))
        self.p2.setStyleSheet("font: 26pt \"Noto Mono\";\n"
"background-color: rgb(200, 115, 189);")
        self.p2.setObjectName("p2")
        self.p2.clicked.connect(self.menu)
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(10, 270, 341, 221))
        self.l4.setText("")
        self.l4.setPixmap(QtGui.QPixmap(":/iage/Bill Payment.jpg"))
        self.l4.setScaledContents(True)
        self.l4.setObjectName("l4")
        self.p3 = QtWidgets.QPushButton(self.centralwidget)
        self.p3.setGeometry(QtCore.QRect(20, 500, 301, 51))
        self.p3.setStyleSheet("font: 26pt \"Noto Mono\";\n"
"background-color: rgb(200, 195, 55);")
        self.p3.setObjectName("p3")
        self.p3.clicked.connect(self.bill)
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(380, 270, 341, 221))
        self.l5.setText("")
        self.l5.setPixmap(QtGui.QPixmap(":/iage/history.jpg"))
        self.l5.setScaledContents(True)
        self.l5.setObjectName("l5")
        self.p5 = QtWidgets.QPushButton(self.centralwidget)
        self.p5.setGeometry(QtCore.QRect(420, 500, 261, 51))
        self.p5.setStyleSheet("font: 26pt \"Noto Mono\";\n"
"background-color: rgb(191, 122, 200);")
        self.p5.setObjectName("p5")
        self.p5.clicked.connect(self.history)
        HomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 21))
        self.menubar.setObjectName("menubar")
        HomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomeWindow)
        self.statusbar.setObjectName("statusbar")
        HomeWindow.setStatusBar(self.statusbar)
        self.actionProfile = QtWidgets.QAction(HomeWindow)
        self.actionProfile.setObjectName("actionProfile")

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)
    def Room(self):
        self.RoomWindow = QtWidgets.QMainWindow()
        self.ui = Ui_RoomWindow(self.a)
        self.ui.setupUi(self.RoomWindow)
        self.RoomWindow.show()
    def menu(self):
        self.FoodWindow = QtWidgets.QMainWindow()
        self.ui = Ui_FoodWindow(self.a)
        self.ui.setupUi(self.FoodWindow)
        self.FoodWindow.show()
    def bill(self):
        self.BillWindow = QtWidgets.QMainWindow()
        self.ui = Ui_BillWindow(self.a)
        self.ui.setupUi(self.BillWindow)
        self.BillWindow.show()
    def history(self):
        self.HistoryWindow = QtWidgets.QMainWindow()
        self.ui = Ui_HistoryWindow(self.a)
        self.ui.setupUi(self.HistoryWindow)
        self.HistoryWindow.show()
    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "Home-Page"))
        self.p1.setText(_translate("HomeWindow", "Room Booking"))
        self.p2.setText(_translate("HomeWindow", "Order Food"))
        self.p3.setText(_translate("HomeWindow", "Pay Your Bill"))
        self.p5.setText(_translate("HomeWindow", "Your History"))
        self.actionProfile.setText(_translate("HomeWindow", "Profile"))
import test

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeWindow = QtWidgets.QMainWindow()
    ui = Ui_HomeWindow()
    ui.setupUi(HomeWindow)
    HomeWindow.show()
    sys.exit(app.exec_())
