# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import test
from PyQt5 import QtCore, QtGui, QtWidgets
from signup import Ui_SignWindow
from homepage import Ui_HomeWindow
import mysql.connector as MC
con=MC.connect(host='localhost',user='root',passwd='',database='hotel')
cur=con.cursor()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("LogIn")
        LogIn.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(LogIn)
        self.centralwidget.setObjectName("centralwidget")
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(0, 0, 791, 571))
        self.l6.setStyleSheet("image: url(:/iage/The-Oberoi-Udaivilas,-Udaipur__2018_Premier-Lake-View-Rooms-with-Semi-Private-Pools---The-Oberoi-Udaivilas,-Udaipur-01.jpg);")
        self.l6.setText("")
        self.l6.setPixmap(QtGui.QPixmap(":/iage/The-Oberoi-Udaivilas,-Udaipur__2018_Premier-Lake-View-Rooms-with-Semi-Private-Pools---The-Oberoi-Udaivilas,-Udaipur-01.jpg"))
        self.l6.setScaledContents(True)
        self.l6.setObjectName("l6")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(170, 50, 191, 41))
        self.l1.setStyleSheet("font: 26pt \"Noto Mono\";\n"
"background-color: rgb(255, 255, 255);")
        self.l1.setObjectName("l1")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(160, 150, 191, 41))
        self.l3.setStyleSheet("font: 26pt \"Noto Mono\";\n"
"background-color: rgb(255, 255, 255);")
        self.l3.setObjectName("l3")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(240, 100, 261, 31))
        self.l2.setStyleSheet("font: 16pt \"Noto Mono\";\n"
"background-color: rgb(255, 255, 255);")
        self.l2.setObjectName("l2")
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(370, 50, 191, 41))
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QLineEdit(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(360, 150, 191, 41))
        self.t2.setObjectName("t2")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(160, 200, 411, 31))
        self.l4.setStyleSheet("font: 16pt \"Noto Mono\";\n"
"background-color: rgb(255, 255, 255);")
        self.l4.setObjectName("l4")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(240, 50, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(290, 260, 171, 51))
        self.b1.setStyleSheet("font: 26pt \"Noto Mono\";\n"
"background-color: rgb(85, 255, 255);")
        self.b1.setObjectName("b1")
        self.b1.clicked.connect(self.login)
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(50, 330, 651, 31))
        self.l5.setStyleSheet("font: 16pt \"Noto Mono\";\n"
"background-color: rgb(255, 255, 255);")
        self.l5.setObjectName("l5")
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(290, 370, 161, 51))
        self.b2.setStyleSheet("font: 16pt \"Noto Mono\";\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.b2.setObjectName("b2")
        self.b2.clicked.connect(self.show2)
        self.l7 = QtWidgets.QLabel(self.centralwidget)
        self.l7.setGeometry(QtCore.QRect(110, 460, 551, 41))
        self.l7.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"text-decoration: underline;")
        self.l7.setText("")
        self.l7.setObjectName("l7")
        self.graphicsView.raise_()
        self.l6.raise_()
        self.l1.raise_()
        self.l3.raise_()
        self.l2.raise_()
        self.t1.raise_()
        self.t2.raise_()
        self.l4.raise_()
        self.b1.raise_()
        self.l5.raise_()
        self.b2.raise_()
        self.l7.raise_()
        LogIn.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LogIn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        LogIn.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LogIn)
        self.statusbar.setObjectName("statusbar")
        LogIn.setStatusBar(self.statusbar)

        self.retranslateUi(LogIn)
        QtCore.QMetaObject.connectSlotsByName(LogIn)
    def login(self):
        self.u=str(self.t1.text()) #Username
        self.p=str(self.t2.text())  #password
        sql="select Email,Password from Data"
        cur.execute(sql)
        rows=cur.fetchall()
        for i in rows:
            if (self.u in i) and (self.p in i):
                self.show1()
            elif (self.u in i) or (self.p in i):
                self.l7.setText("Username or Password wrong, please retry.")
            else:
                self.l7.setText("Please sign up.")
    def show1(self):
        try:
            self.HomeWindow = QtWidgets.QMainWindow()
            self.ui = Ui_HomeWindow(self.u)
            self.ui.setupUi(self.HomeWindow)
            self.HomeWindow.show()
        except:
            print("error")
    def show2(self):
        try:
            self.SignWindow = QtWidgets.QMainWindow()
            self.ui = Ui_SignWindow()
            self.ui.setupUi(self.SignWindow)
            self.SignWindow.show()
        except:
            print("error")
    def retranslateUi(self, LogIn):
        _translate = QtCore.QCoreApplication.translate
        LogIn.setWindowTitle(_translate("LogIn", "Log-In"))
        self.l1.setText(_translate("LogIn", "Username:"))
        self.l3.setText(_translate("LogIn", "Password:"))
        self.l2.setText(_translate("LogIn", "Same as your e-mail."))
        self.l4.setText(_translate("LogIn", "Same as you gave during Sign Up."))
        self.b1.setText(_translate("LogIn", "Log In"))
        self.l5.setText(_translate("LogIn", "If you are not registered then please click below."))
        self.b2.setText(_translate("LogIn", "Sign Up"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogIn = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(LogIn)
    LogIn.show()
    sys.exit(app.exec_())
