# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RoomBooking.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from datetime import date
import random
import mysql.connector as MC
con=MC.connect(host='localhost',user='root',passwd='',database='hotel')
cur=con.cursor()
import test
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RoomWindow(object):
    def __init__(self,x):
        self.b=x
    def setupUi(self, RoomWindow):
        RoomWindow.setObjectName("RoomWindow")
        RoomWindow.resize(788, 600)
        self.centralwidget = QtWidgets.QWidget(RoomWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(0, 0, 791, 561))
        self.l1.setText("")
        self.l1.setPixmap(QtGui.QPixmap(":/iage/Login Room.jpg"))
        self.l1.setScaledContents(True)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(240, 220, 261, 21))
        self.l2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l2.setObjectName("l2")
        self.p1 = QtWidgets.QPushButton(self.centralwidget)
        self.p1.setGeometry(QtCore.QRect(130, 270, 191, 31))
        self.p1.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(69, 255, 66);")
        self.p1.setObjectName("p1")
        self.p1.clicked.connect(self.ac)
        self.p2 = QtWidgets.QPushButton(self.centralwidget)
        self.p2.setGeometry(QtCore.QRect(390, 270, 221, 31))
        self.p2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(119, 121, 255);")
        self.p2.setObjectName("p2")
        self.p2.clicked.connect(self.nonac)
        self.d1 = QtWidgets.QDateEdit(self.centralwidget)
        self.d1.setGeometry(QtCore.QRect(390, 130, 110, 22))
        self.d1.setObjectName("d1")
        self.d2 = QtWidgets.QDateEdit(self.centralwidget)
        self.d2.setGeometry(QtCore.QRect(390, 180, 110, 22))
        self.d2.setObjectName("d2")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(240, 130, 111, 21))
        self.l4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l4.setObjectName("l4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 180, 121, 21))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(120, 340, 481, 31))
        self.l6.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"background-color: rgb(255, 255, 255);")
        self.l6.setText("")
        self.l6.setObjectName("l6")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(40, 70, 691, 31))
        self.l3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"background-color: rgb(255, 255, 255);")
        self.l3.setObjectName("l3")
        RoomWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RoomWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 21))
        self.menubar.setObjectName("menubar")
        RoomWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RoomWindow)
        self.statusbar.setObjectName("statusbar")
        RoomWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RoomWindow)
        QtCore.QMetaObject.connectSlotsByName(RoomWindow)

    def ac(self):
        self.ci=(self.d1.text()).split('/')
        self.co=(self.d2.text()).split('/')
        fd=date(int(self.ci[2]),int(self.ci[0]),int(self.ci[1]))
        sd=date(int(self.co[2]),int(self.co[0]),int(self.co[1]))
        if self.ci[0]<=self.co[0] and self.co[1]<self.ci[1]:
            self.l3.setText("Wrong Date given. Please try again")
        else:
            if sd>fd:
                delta=sd-fd
            else:
                delta=fd-sd
            self.a=delta.days*700
        sql="insert into Booking values('{}',{},'{}','{}','{}',{},'{}')".format(self.b,random.randint(1,150),'AC Room',self.ci[2]+'/'+self.ci[0]+'/'+self.ci[1],self.co[2]+'/'+self.co[0]+'/'+self.co[1],self.a,"No")
        cur.execute(sql)
        con.commit()
        self.l6.setText("Succesfully Booked.")
    def nonac(self):
        self.ci=(self.d1.text()).split('/')
        self.co=(self.d2.text()).split('/')
        fd=date(int(self.ci[2]),int(self.ci[0]),int(self.ci[1]))
        sd=date(int(self.co[2]),int(self.co[0]),int(self.co[1]))
        if self.ci[0]<=self.co[0] and self.co[1]<self.ci[1]:
            self.l3.setText("Wrong Date given. Please try again")
        else:
            if sd>fd:
                delta=sd-fd
            else:
                delta=fd-sd
            self.a=delta.days*500
        sql="insert into Booking values('{}',{},'{}','{}','{}',{},'{}')".format(self.b,random.randint(151,300),'Non-AC Room',self.ci[2]+'/'+self.ci[0]+'/'+self.ci[1],self.co[2]+'/'+self.co[0]+'/'+self.co[1],self.a,"No")
        cur.execute(sql)
        con.commit()
        self.l6.setText("Succesfully Booked.")
    def retranslateUi(self, RoomWindow):
        _translate = QtCore.QCoreApplication.translate
        RoomWindow.setWindowTitle(_translate("RoomWindow", "Room-Booking"))
        self.l2.setText(_translate("RoomWindow", "There are two types of Rooms."))
        self.p1.setText(_translate("RoomWindow", "1.AC Rooms : ₹700"))
        self.p2.setText(_translate("RoomWindow", "2.Non-AC Rooms : ₹500"))
        self.l4.setText(_translate("RoomWindow", "Check-In Date :"))
        self.label.setText(_translate("RoomWindow", "Check-Out Date : "))
        self.l3.setText(_translate("RoomWindow", "Please Provide the dates in the format mm/dd/yyyy. Then select the room type to book the room."))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RoomWindow = QtWidgets.QMainWindow()
    ui = Ui_RoomWindow()
    ui.setupUi(RoomWindow)
    RoomWindow.show()
    sys.exit(app.exec_())
