# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import test
from homepage import Ui_HomeWindow
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as MC
con=MC.connect(host='localhost',user='root',passwd='',database='hotel')
cur=con.cursor()

class Ui_SignWindow(object):
    def setupUi(self, SignWindow):
        SignWindow.setObjectName("SignWindow")
        SignWindow.resize(789, 584)
        self.centralwidget = QtWidgets.QWidget(SignWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(0, -10, 801, 631))
        self.l1.setText("")
        self.l1.setPixmap(QtGui.QPixmap(":/iage/sign up image.jpg"))
        self.l1.setScaledContents(True)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(240, 40, 51, 21))
        self.l2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l2.setObjectName("l2")
        self.b1 = QtWidgets.QLineEdit(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(350, 40, 113, 20))
        self.b1.setObjectName("b1")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(250, 80, 41, 21))
        self.l3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l3.setObjectName("l3")
        self.b2 = QtWidgets.QLineEdit(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(350, 80, 113, 20))
        self.b2.setObjectName("b2")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(210, 120, 81, 20))
        self.l4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l4.setObjectName("l4")
        self.b3 = QtWidgets.QLineEdit(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(350, 120, 141, 20))
        self.b3.setObjectName("b3")
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(230, 170, 61, 21))
        self.l5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l5.setObjectName("l5")
        self.b4 = QtWidgets.QLineEdit(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(350, 170, 251, 20))
        self.b4.setObjectName("b4")
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(210, 220, 81, 16))
        self.l6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l6.setObjectName("l6")
        self.b5 = QtWidgets.QLineEdit(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(350, 220, 191, 20))
        self.b5.setObjectName("b5")
        self.l7 = QtWidgets.QLabel(self.centralwidget)
        self.l7.setGeometry(QtCore.QRect(110, 250, 601, 21))
        self.l7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l7.setObjectName("l7")
        self.l8 = QtWidgets.QLabel(self.centralwidget)
        self.l8.setGeometry(QtCore.QRect(150, 290, 141, 21))
        self.l8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l8.setObjectName("l8")
        self.b6 = QtWidgets.QLineEdit(self.centralwidget)
        self.b6.setGeometry(QtCore.QRect(350, 290, 191, 20))
        self.b6.setObjectName("b6")
        self.l9 = QtWidgets.QLabel(self.centralwidget)
        self.l9.setGeometry(QtCore.QRect(240, 320, 211, 16))
        self.l9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.l9.setObjectName("l9")
        self.p1 = QtWidgets.QPushButton(self.centralwidget)
        self.p1.setGeometry(QtCore.QRect(280, 350, 121, 41))
        self.p1.setStyleSheet("background-color: rgb(157, 209, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.p1.setObjectName("p1")
        self.p1.clicked.connect(self.sign)
        SignWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        SignWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SignWindow)
        self.statusbar.setObjectName("statusbar")
        SignWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SignWindow)
        QtCore.QMetaObject.connectSlotsByName(SignWindow)
    def sign(self):
        n=str(self.b1.text()) #name 
        a=int(self.b2.text())  #age 
        p=str(self.b3.text())  # phone no.
        e=str(self.b4.text())  #email 
        pas=str(self.b5.text()) # password
        sql="insert into Data values('{}',{},'{}','{}','{}')".format(n,a,p,e,pas)
        cur.execute(sql)
        con.commit()
        try:
            self.HomeWindow = QtWidgets.QMainWindow()
            self.ui = Ui_HomeWindow(e)
            self.ui.setupUi(self.HomeWindow)
            self.HomeWindow.show()
        except:
            print("error")
    def retranslateUi(self, SignWindow):
        _translate = QtCore.QCoreApplication.translate
        SignWindow.setWindowTitle(_translate("SignWindow", "Sign-Up"))
        self.l2.setText(_translate("SignWindow", "Name:"))
        self.l3.setText(_translate("SignWindow", "Age:"))
        self.l4.setText(_translate("SignWindow", "Phone no.:"))
        self.l5.setText(_translate("SignWindow", "E-mail:"))
        self.l6.setText(_translate("SignWindow", "Password:"))
        self.l7.setText(_translate("SignWindow", "*Must be a combination of Special charactes, Lower case, Upper case and Numerics."))
        self.l8.setText(_translate("SignWindow", "Confirm Password:"))
        self.l9.setText(_translate("SignWindow", "*Must be same as Password."))
        self.p1.setText(_translate("SignWindow", "Sign-Up"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignWindow = QtWidgets.QMainWindow()
    ui = Ui_SignWindow()
    ui.setupUi(SignWindow)
    SignWindow.show()
    sys.exit(app.exec_())
